ARG PHP_VERSION
ARG PHP_DISTRO

FROM php:${PHP_VERSION}-fpm-${PHP_DISTRO}

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN set -ex \
    && chmod +x /usr/local/bin/install-php-extensions \
    && find / \( -path /dev -o -path /sys -o -path /proc \) -prune -o \( -type f -o -type l \) -print | sort > /.php.base
