ARG PHP_VERSION
ARG PHP_DISTRO
ARG DOCKER_REPO

FROM ${DOCKER_REPO}/php:${PHP_VERSION}-${PHP_DISTRO}-build as build

ARG PHP_EXT
RUN set -ex \
    && install-php-extensions ${PHP_EXT}

RUN set -ex \
    && find / \( -path /dev -o -path /sys -o -path /proc \) -prune -o \( -type f -o -type l \) -print | sort > /.php.ext \
    && mkdir /build \
    && comm -23 /.php.ext /.php.base | xargs -ri cp --parents {} /build || true

FROM scratch

COPY --from=build /build/ /
